'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function LoginPage() {
  const supabase=createClient(), router=useRouter()
  const [mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');if(mode==='login'){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else{router.push('/dashboard');router.refresh()}}else{const{error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:`${location.origin}/auth/callback`}});setMsg(error?error.message:'Check your email to confirm. An admin must then approve your account.')}setBusy(false)}
  return <main className="login-wrap"><section className="login-card"><div className="login-brand"><div className="login-mark">KJ</div><div><h1 className="login-title">KJS CRM</h1><p className="login-copy">Creative business management</p></div></div><h2 className="login-heading">{mode==='login'?'Welcome back':'Create your account'}</h2><p className="login-description">{mode==='login'?'Sign in to manage leads, clients and projects.':'Join your KJS Creative workspace.'}</p><form onSubmit={submit}>{mode==='signup'&&<div className="field"><label>Full name</label><input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} required /></div>}<div className="field"><label>Email address</label><input type="email" placeholder="you@company.com" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" /></div><div className="field"><label>Password</label><input type="password" placeholder="••••••••" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} autoComplete={mode==='login'?'current-password':'new-password'} /></div><button className="primary-button" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in to CRM':'Create account'}</button>{msg&&<p className="alert" role="alert">{msg}</p>}</form><p className="toggle">{mode==='login'?'New to KJS CRM? ':'Already have an account? '}<button type="button" onClick={()=>{setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?'Create an account':'Sign in instead'}</button></p><div className="secure-note">◉ Secure workspace · Powered by Supabase</div></section></main>
}
