'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function LoginPage() {
  const supabase=createClient(), router=useRouter()
  const [mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[showPassword,setShowPassword]=useState(false)
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');if(mode==='login'){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else{router.push('/dashboard');router.refresh()}}else{const{error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:`${location.origin}/auth/callback`}});setMsg(error?error.message:'Check your email to confirm. An admin must then approve your account.')}setBusy(false)}
  return <main className="login-page"><section className="login-hero"><div className="login-hero-brand"><span className="login-logo">KJ</span><span>KJS Creative</span></div><div className="login-hero-copy"><h2>Every lead,<br/>one clear view.</h2><p>Track leads, clients, projects and invoices in one calm workspace built for the KJS team.</p></div><small>Private workspace · authorised team only</small></section><section className="login-side"><form className="login-form" onSubmit={submit}><div><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p className="login-sub">{mode==='login'?'Sign in to your CRM account.':'Join your KJS Creative workspace.'}</p></div>{mode==='signup'&&<label>Full name<input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} required /></label>}<label>Email<input type="email" placeholder="you@kjscreative.in" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" /></label><label>Password<span className="password-field"><input type={showPassword?'text':'password'} placeholder="••••••••" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} autoComplete={mode==='login'?'current-password':'new-password'} /><button type="button" className="password-toggle" onClick={()=>setShowPassword(!showPassword)}>{showPassword?'Hide':'Show'}</button></span></label>{mode==='login'&&<div className="login-row"><label className="remember"><input type="checkbox"/> Remember me</label><button type="button" className="forgot" onClick={()=>setMsg('Password reset can be configured from Supabase Auth.')}>Forgot password?</button></div>}<button className="login-button" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button>{msg&&<p className="login-alert" role="alert">{msg}</p>}<p className="login-foot">{mode==='login'?'No account? Ask an admin to invite you.':'Already have an account? '} {mode==='login'&&<button type="button" onClick={()=>{setMode('signup');setMsg('')}}>Create an account</button>}{mode==='signup'&&<button type="button" onClick={()=>{setMode('login');setMsg('')}}>Sign in instead</button>}</p></form></section></main>
}
