'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function LoginPage() {
  const supabase=createClient(), router=useRouter()
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[showPassword,setShowPassword]=useState(false)
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else{router.push('/dashboard');router.refresh()}setBusy(false)}
  return <main className="login-page"><section className="login-hero"><div className="login-hero-brand"><span className="login-logo">KJ</span><span>KJS Creative</span></div><div className="login-hero-copy"><h2>Every lead,<br/>one clear view.</h2><p>Track leads, clients, projects and invoices in one calm workspace built for the KJS team.</p></div><small>Private workspace · authorised team only</small></section><section className="login-side"><form className="login-form" onSubmit={submit}><div><h1>Welcome back</h1><p className="login-sub">Sign in to your CRM account.</p></div><label>Email<input type="email" placeholder="you@kjscreative.in" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" /></label><label>Password<span className="password-field"><input type={showPassword?'text':'password'} placeholder="••••••••" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} autoComplete="current-password" /><button type="button" className="password-toggle" onClick={()=>setShowPassword(!showPassword)}>{showPassword?'Hide':'Show'}</button></span></label><div className="login-row"><label className="remember"><input type="checkbox"/> Remember me</label><button type="button" className="forgot" onClick={()=>setMsg('Password reset can be configured from Supabase Auth.')}>Forgot password?</button></div><button className="login-button" disabled={busy}>{busy?'Please wait…':'Sign in'}</button>{msg&&<p className="login-alert" role="alert">{msg}</p>}<p className="login-foot">Access is restricted to authorised KJS Creative team members.</p></form></section></main>
}
